version: "3"
services:
  app:
    build: .
    working_dir: /app
    volumes:
      - ".:/app"
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - pg
  pg:
    image: postgres:14
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    driver: local